# SPDX-FileCopyrightText: Copyright (c) 2019 Anthony Sottile
# SPDX-FileCopyrightText: Copyright (c) 2021 Piotr "DoomHammer" Gaczkowski for Hackerspace Trójmiasto
#
# SPDX-License-Identifier: MIT
name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ hashFiles('.pre-commit-config.yaml') }}
    - uses: pre-commit/action@v2.0.2
